branches:
  only:
  - master
language: node_js
node_js:
- node
install:
- npm install -g gulp
- npm install
before_script:
- git remote set-url origin git@github.com:timBrockman/static-scratch.git
- git config --global user.email "tim@timbrockman.com"
- git config --global user.name "Travis-CI"
script:
- gulp
env:
  global:
  - ENCRYPTION: "5612014fe239"
  - COMMIT_AUTHOR_EMAIL: "tim@timbrockman.com"
before_install:
- openssl aes-256-cbc -K $encrypted_5612014fe239_key -iv $encrypted_5612014fe239_iv
  -in deploy_key.enc -out deploy_key -d
notifications:
  email: false