branches:
  only:
    - master
language: node_js
node_js:
  - "node"
install:
  - npm install -g gulp
  - npm install
before_script:
  - git remote set-url origin "https://${GH_TOKEN@github.com/}"
  - git config --global user.email "tim@timbrockman.com"
  - git config --global user.name "Travis-CI"
script:
  - gulp deploy
env:
  global:
    - secure: ""